baseURL = "http://mypalmike.github.io/"
languageCode = "en-us"
title = "mypalmike"
theme = "terminal"
paginate = 5
summaryLength = 20
copyright = "© 2024 mypalmike. All rights reserved. Made with Hugo with theme Terminal."

[params]
Logo.logoText = "mypalmike"
centerTheme = true
themeColor = "green"
ReadMore = "Read More..."

[[menu.main]]
name = "Home"
weight = 10
url = "/"
[[menu.main]]
name = "My Work"
weight = 20
url = "/work"
[[menu.main]]
name = "Tech Blog"
weight = 30
url = "/tech_blog"
[[menu.main]]
name = "Writing"
weight = 40
url = "/writing"
[[menu.main]]
name = "Caption Contest"
weight = 50
url = "/captions"
